#!/bin/sh

# Easily switch between `io.js` and `Node.js`
alias use-iojs="brew unlink node && brew link --force iojs"
alias use-node="brew unlink iojs && brew link --force node"

alias npu_dev="npm uninstall --save-dev"
alias npu_g="npm uninstall -g"
alias npu="npm uninstall"

alias npi="npm install"
alias n="npm"
alias npi_dev="npm install --save-dev"
alias nr_test="npm run test"
alias nr_start="npm run start"

alias y="yarn"
alias ys="yarn start"
alias yst="yarn start"
alias ysb="yarn storybook"
alias ys1="yarn login --registry=https://packages.atlassian.com && yarn install && yarn start"
alias yt="yarn test"
alias yj="yarn jest"
alias yjw="yarn jest:watch"
alias yb="yarn build"
alias yd="yarn deploy"
alias yl="yarn lint"
alias ytw="yarn test:watch"
alias yf="yarn format"
alias ypf="yarn prettier:fix"
alias yr="yarn run"
alias y="yarn"
alias ya="yarn add"
alias yad="yarn add --dev"
alias yap="yarn add --peer"
alias yb="yarn build"
alias ycc="yarn cache clean"
alias yga="yarn global add"
alias ygls="yarn global list"
alias ygrm="yarn global remove"
alias ygu="yarn global upgrade"
alias yh="yarn help"
alias yi="yarn init"
alias yin="yarn install"
alias yls="yarn list"
alias yout="yarn outdated"
alias yp="yarn pack"
alias yrm="yarn remove"
alias yrun="yarn run"
# alias ys="yarn serve"
alias yt="yarn test"
alias yuc="yarn global upgrade && yarn cache clean"
alias yui="yarn upgrade-interactive"
alias yup="yarn upgrade"


alias sls="serverless"
alias sls="serverless"
alias b="bolt"
